### ISSUE TITLE
Script stops working

### ISSUE THREAD

**Issue by mxywes** [natinusala/spotify-library-blind-test#2]
![Screenshot](https://vgy.me/4RRZs3.png)
When I click next, some songs just doesn't play the sample, the timer freezes to 30, and you can just press 'Give up' to get the next song. The javascript console displays an error, as well as the network tab in the Developers Tools. I'm too lazy to study the source to see where the issue might be, so I'm just reporting.
```
GET https://natinusala.github.io/spotify-library-blind-test/null 404 () null:1
Uncaught (in promise) DOMException: Failed to load because no supported source was found. VM462 :1
Promise (async)
startGameForNewSong @spotify-blind-test.js:377
nextSong @spotify-blind-test.js:326
onclick @VM545 :138
```
EDIT: found out it happens on a per-artist basis, some artists are bugged for a whole session, while some others work just fine.

**Comment by natinusala** [comment]
I should check if the MP3 will HTTP != 200 before launching the song, and if it's != 200 I pick another song.
